---
title: "Cluster Comparisons"
output: html_document
---

```{r}
library(tidyverse)
library(cowplot)
library(funtimes)
library(aricode)
library(DT)
```

```{r}
n <- 1000
seed <- 42
data_dir <- file.path('data', paste(n, seed, sep='_'))
```

```{r}
clusters <- list.files(data_dir)
clusters <- clusters[grepl('^clusters_', clusters)]

comments <- read.csv(file.path(data_dir, 'comments_sample.csv')) %>%
  select(-dupe_count)
comments <- lapply(clusters, function(fn) {
  cl <- read.csv(file.path(data_dir, fn)) %>% select(docid, cluster)
  key <- sub('clusters_(.*).csv', '\\1', fn)
  colnames(cl) <- c('docid', key)
  return(cl)
}) %>% 
  reduce(inner_join, by='docid') %>% inner_join(comments, by='docid') %>%
  gather(key='cluster_method', value='cluster_id', -docid, -text_data, -is_astroturf)

head(comments)
```


```{r, echo=FALSE}
numericInput("rows", "How many cars?", 5)

renderTable({
  head(comments, input$rows)
})
```


```{r fig1, fig.width=12, fig.height=8}
ggplot(comments, aes(cluster_id)) +
  facet_wrap(~cluster_method, scales='free_x', ncol=4) + 
  geom_bar()
```

# Clustering Purity

We can use Kao's annotated corpus as classes, however the fact that there are more classes than clusters for each method creates a problem. 

```{r}
classes <- as.factor(comments[comments$cluster_method=='level_0_cluster',]$cluster_id)
methods <- unique(comments[comments$cluster_method!='level_0_cluster',]$cluster_method)
scores <- sapply(methods, function(method) {
  clusters <- as.factor(comments[comments$cluster_method==method,]$cluster_id)
  out <- list(purity=purity(classes,clusters)$pur,
              'normalized mutual information'=NMI(classes, clusters),
              'adjusted rand index'=ARI(classes, clusters))
  return(out)
})
scores
```

## Kao Clusters
Clusters identified by Kao using signature strings

```{r}
comments %>% filter(cluster_method=='level_0_cluster' & cluster_id == '1') %>% select(text_data)
```

