#
# util.R
#

library(dplyr)
library(purrr)
library(tidyr)
library(tidyverse)

getClusterResults <- function(data_dir) {
    # Get results of all clustering done on this sample of the dataset
    #
    # Args:
    #    data_dir: the parent directory for all CSV files generated by cluster_calculations.Rmd
    #
    # Return:
    #   a dataframe
    clusters <- getClusters(data_dir)
    comments <- read.csv(file.path(data_dir, 'comments_sample.csv')) %>%
        select(-dupe_count)

    comments <- lapply(clusters, function(fn) {
        cl <- read.csv(file.path(data_dir, fn)) %>% select(docid, cluster)
        key <- sub('clusters_(.*).csv', '\\1', fn)
        colnames(cl) <- c('docid', key)
        return(cl)
    })  %>% 
    reduce(inner_join, by='docid') %>% 
    inner_join(comments, by='docid') %>%
    gather(key='method', value='cluster_id', -docid, -text_data) %>%
    
    # This is the price I pay for not incrementing Kao's cluster ids :(
    mutate(is_astroturf = ifelse(method == 'level_0' & cluster_id != -1, TRUE, 
                          ifelse(method != 'level_0' & cluster_id != 0, TRUE, 
                          FALSE)))
    
    comments$is_astroturf <- as.factor(comments$is_astroturf)
    comments$cluster_id <- as.factor(comments$cluster_id)
    comments$docid <- as.factor(comments$docid)
    comments$method <- as.factor(comments$method)
    
    return(comments)
}

getClusters <- function(parent_dir) {
    cluster_fns <- list.files(parent_dir)
    clusters <- cluster_fns[grepl('^clusters_', cluster_fns)]
    return(clusters)
}

calcRand <- function(corpus, rexp=NULL) {
    # Calculate adjusted Rand index
    #
    # Args:
    #   corpus: a tidytext dataframe to calculate clusters upon. It must include the 
    #           method and is_astroturf columns
    #   rexp: A regular expression to filter methods against (optional)
    #
    # Return:
    #   Dataframe
    if (!is.null(rexp)) {
        corpus <- corpus %>% filter(str_detect(method, rexp))
    }
    classes <- as.factor(corpus[corpus$method=='level_0',]$is_astroturf)
    methods <- unique(corpus[corpus$method!='level_0',]$method)
    scores <- sapply(methods, function(method) {
        clusters <- corpus[corpus$method==method,]$is_astroturf
        return(ARI(classes, clusters))
    })
    out <- data.frame(method=methods, rand=scores)
    rownames(out) <- NULL
    
    out <- out %>% mutate(vec=ifelse(str_starts(method, 'pos|dak'), 'part of speech', 
                    ifelse(str_starts(method, 'word'), 'word', 
                    'misc')))
    
    return(out)
}